print("My Daily Routine)
print("I wake up at 6:30 AM")
print("I go to school at 7:30 AM")
print("I come back from school at 5:15 PM")
print("I attend Codingal class at 6:00 PM")
print("I do my homwork till 8:15 PM")
print("I eat dinner at 8:30 PM")
print("I watch TV till 9:00 PM")
print("I sleep at 10:00 PM")